config/routes.rb
Trackbeerfests::Application.routes.draw do

  root 'users#index'

  resources :users
  get 'signup', :to => 'users#signup'
  get 'success', :to => 'users#success'
  get 'thanks', :to => 'users#thanks'

  resources :events
  get 'show', :to => 'events#show'

  resources :breweries
  get 'show', :to => 'breweries#show'

  resources :beers, :collection => { :select_event => :put }
  get 'show', :to => 'beers#show'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	#serialize :event_id
	belongs_to :brewery
	has_many :beer_supplies
	has_many :events, :through => :beer_supplies
end

app/models/beer_supply.rb
class BeerSupply < ActiveRecord::Base
	belongs_to :beer
	belongs_to :event
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	has_many :beers

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :beer_supplies
	has_many :beers, :through => :beer_supplies
end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, :format=> { :with=> VALID_EMAIL_REGEX , :message=> 'Enter your Email Address' }
	validates :email, uniqueness: {:case_sensitive => false, :message => 'Please provide a valid Email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

	def index
		@beers = Beer.all
	end

	def new
		@beer = Beer.new
	end

	def create
		@beer = Beer.create(beer_params)
		redirect_to beers_path
	end

	def show
		@beer = Beer.find(params[:id])
		@brewery = Brewery.find(Beer.find(params[:id]).brewery_id)
		@events = Event.all
		@beer_events = Beer.find(params[:id]).event_id

		@beer_supplies = BeerSupply.all
	end

	def edit
		@beer = Beer.find(params[:id])
		@events = Event.all
	end

	def update
		puts "update: #{params.inspect}"
		@beer = Beer.find(params[:id])
		@event_id = Beer.find(params[:id]).event_id
		
		#work on this
		@events = params['event_ids']

		new_arr = []

		@events.each do |event|
			begin
				BeerSupply.create!(beer_id: @beer.id, event_id: event.to_i)
			rescue => e
			  puts "#{e.message} #{e.backtrace}"
			end

			#list of all beer supply pairings: BeerSupply.where(beer_id: @beer.id, event_id: @event.id)
			#(beer_id: 2, event_id: 2) that didn’t belong
			#delete on those records

			new_arr  << event.to_i
		end
		#end work on this

		#Only stores 1 value because field is an int. How do we store multiple events? Need to convert field in DB to string?
		#@beer.update_attributes(:event_id => new_arr)

		@beer.update_attributes(beer_params)
		redirect_to beer_path(@beer)


	end

	def select_event

	end


	private

	def beer_params
		params.require(:beer).permit(:beer_name, :beer_style, :beer_abv, :beer_ibu, :beer_description, :brewery_id, :event_id)
	end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

	def index
		@breweries = Brewery.all
	end

	def new
		@brewery = Brewery.new
	end

	def create
		@brewery = Brewery.create(brewery_params)
		redirect_to breweries_path
	end

	def show
		@brewery = Brewery.find(params[:id])
		@beers = Beer.all
	end

	def edit
		@brewery = Brewery.find(params[:id])
	end

	def update
		@brewery = Brewery.find(params[:id])
		@brewery.update_attributes(brewery_params)
		redirect_to breweries_path
	end



	private

	def brewery_params
		params.require(:brewery).permit(:brewery_name, :brewery_address, :brewery_city, :brewery_state, :brewery_zip, :brewery_website, :brewery_twitter, :brewery_facebook, :brewery_description)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		Event.create(event_params)
		redirect_to events_path
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@event.update_attributes(event_params)
		redirect_to events_path
	end


	private

	def event_params
		params.require(:event).permit(:event_name, :event_loc_name, :event_loc_address, :event_loc_city, :event_loc_state, :event_loc_zip, :event_start_date, :event_end_date, :event_website, :event_description)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
	end

	def signup
		@user = User.new
	end

	def create
	    @user = User.create(user_params)
	    if @user.invalid?
	      flash[:error] = '<strong>Email address invalid.</strong>'
	      redirect_to signup_path
	    else
	      flash[:success] = '<strong>You have signed up for priority access.</strong>'
	      redirect_to success_path
	    end
	end

	def thanks
	end

	def success
	end


	private

	def user_params
		params.require(:user).permit(:email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Update Beer Details</h1>
	<%= simple_form_for @beer do |f| %>
    <%= f.input :beer_name %>
    <%= f.label "Brewery name" %>
    <br />
    <%= f.collection_select :brewery_id, Brewery.all, :id, :brewery_name, prompt: true %>
    <%= f.input :beer_style %>
    <%= f.input :beer_abv %>
    <%= f.input :beer_ibu %>
    <%= f.label "Select events" %>
    <br />
    

    <% for event in @events %>
        <li>
            <%= check_box_tag 'event_ids[]', event.id, (checked = true if event.beer_supplies.includes(@beer.id)) %>
            <%= event.event_name %>
        </li>
    <% end %>

    
    <%= f.input :beer_description %>
    <br />
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/beers/index.html.erb
<% @beers.each do |beer| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h2><%= link_to beer.beer_name, beer_path(beer) %></h2>
    <h5><%= Brewery.find(beer.brewery_id).brewery_name %></h5><br />
    <p>
    	<strong><%= beer.beer_style %></strong><br />
    	<%= beer.beer_abv %>% ABV &nbsp;|&nbsp; <%= beer.beer_ibu %> IBU
    </p>
    <%= link_to 'More Info', beer_path(beer), :class => 'btn btn-primary pull-right', :role => 'button' %>
  </div>

<% end %>

app/views/beers/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Beer Details</h1>
	<%= simple_form_for @beer do |f| %>
    <%= f.input :beer_name %>
    <%= f.input :beer_style %>
    <%= f.input :beer_abv %>
    <%= f.input :beer_ibu %>
    <%= f.input :beer_description %>
    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/beers/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1><%= @beer.beer_name %></h1>
	<h4><%= link_to @brewery.brewery_name, brewery_path(@brewery) %></h4><br />
	<p><strong><%= @beer.beer_style %></strong><br />
	<%= @beer.beer_abv %>% ABV &nbsp;|&nbsp; <%= @beer.beer_ibu %> IBU</p><br />
	<p><%= @beer.beer_description %></p>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<br /><br />
	<h2>Events Serving <%= @beer.beer_name %></h2>
	<br />
	<% x = 0 %>
	<% @events.each do |event| %>
		<% if @beer.event_id == nil %>
			No events listed. Please check back later.
		<% elsif event.id == @beer.event_id %>
			<strong><%= link_to event.event_name, event_path(event) %></strong><br />
			<%= event.event_start_date.strftime("%A, %B %d, %Y") %><br />
			<%= event.event_loc_city %>, <%= event.event_loc_state %>
			<% x = x + 1 %>
			<hr />
		<% end %>
	<% end %>
</div>


<div class="col-xs-10 col-xs-offset-1">
	<br /><br />
	<h2>TEST EVENT LISTING</h2>
	<br />
	BEER EVENTS: <%= @beer_events.inspect %>
	<%# @beer_events.each do |event| %>
	<%#= puts event %>
	<%# end %>
</div>


<div class="col-xs-10 col-xs-offset-1">
	<br /><br />
	<h2>BEER SUPPLIES</h2>
	<br />
	BEER SUPPLIES:
	<%= @beer_supplies.inspect %>
	<% @beer_supplies.each do |listing| %>
		<% if listing.beer_id == @beer.id %>
			<%#= @events(listing.event_id).event_name %>
		<% end %>
	<% end %>
</div>

app/views/breweries/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Update Brewery Details</h1>
	<br />
	<%= simple_form_for @brewery do |f| %>
    <%= f.input :brewery_name %>
    <br />
    <%= f.input :brewery_address %>
    <%= f.input :brewery_city %>
    <%= f.input :brewery_state %>
    <%= f.input :brewery_zip %>
    <br />
    <%= f.input :brewery_website %>
    <%= f.input :brewery_twitter %>
    <%= f.input :brewery_facebook %>
    <br />
    <%= f.input :brewery_description %>
    <br />
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/breweries/index.html.erb
<% @breweries.each do |brewery| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h2><%= link_to brewery.brewery_name, brewery_path(brewery) %></h2>
    <p>
    	<%= brewery.brewery_city %>, <%= brewery.brewery_state %>
    </p>
        <%= link_to 'More Info', brewery_path(brewery), :class => 'btn btn-primary pull-right', :role => 'button' %>
  </div>

<% end %>

app/views/breweries/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Brewery Details</h1>
	<br />
	<%= simple_form_for @brewery do |f| %>
    <%= f.input :brewery_name %>
    <br />
    <%= f.input :brewery_address %>
    <%= f.input :brewery_city %>
    <%= f.input :brewery_state %>
    <%= f.input :brewery_zip %>
    <br />
    <%= f.input :brewery_website %>
    <%= f.input :brewery_twitter %>
    <%= f.input :brewery_facebook %>
    <br />
    <%= f.input :brewery_description %>
    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/breweries/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1><%= @brewery.brewery_name %></h1><br />
	<p>
		<%= @brewery.brewery_address %><br/>
		<%= @brewery.brewery_city %>, <%= @brewery.brewery_state %> <%= @brewery.brewery_zip %>
	</p>
	<p>
		<%= link_to "Website", @brewery.brewery_website, :target => "_blank" %>
		<% if @brewery.brewery_facebook != "" %>
			&nbsp;|&nbsp; <%= link_to "Facebook", @brewery.brewery_facebook, :target => "_blank" %>
		<% end %>
		<% if @brewery.brewery_twitter != "" %>
			&nbsp;|&nbsp; <%= link_to "Twitter", @brewery.brewery_twitter, :target => "_blank" %>
		<% end %>
	</p>
	<p>
		<%= @brewery.brewery_description %>
	</p>
</div>

<div class="col-xs-10 col-xs-offset-1">
	<br /><br />
	<h2>Beers from <%= @brewery.brewery_name %></h2>
	<br />
	<% @beers.each do |beer| %>
		<% if beer.brewery_id == @brewery.id %>
			<strong><%= link_to beer.beer_name, beer_path(beer) %></strong><br />
			<%= beer.beer_style %><br />
			<%= beer.beer_abv %>% ABV &nbsp;|&nbsp; <%= beer.beer_ibu %> IBU
			<hr />
		<% end %>
	<% end %>
</div>

app/views/events/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1>
	<%= simple_form_for @event do |f| %>
    <%= f.input :event_name %>

    <br />
    <%= f.input :event_loc_name %>
    <%= f.input :event_loc_address %>
    <%= f.input :event_loc_city %>
    <%= f.input :event_loc_state %>
    <%= f.input :event_loc_zip %>

    <br />
    <%= f.input :event_start_date %>
    <%= f.input :event_end_date %>

    <br />
    <%= f.input :event_website %>
    <%= f.input :event_description %>

    <br />
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h2><%= link_to event.event_name, event_path(event) %></h2><br />
    <p><strong><%= event.event_start_date.strftime("%A, %B %d, %Y") %></strong><br />
    	<%= event.event_loc_name %>
    	<br />
   		<i><%= event.event_loc_city %>, <%= event.event_loc_state %></i>
	</p>
	<%= link_to 'More Info', event_path(event), :class => 'btn btn-primary pull-right', :role => 'button' %>
  </div>

<% end %>

app/views/events/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Beer Details</h1>
	<%= simple_form_for @event do |f| %>
    <%= f.input :event_name %>

    <br />
    <%= f.input :event_loc_name %>
    <%= f.input :event_loc_address %>
    <%= f.input :event_loc_city %>
    <%= f.input :event_loc_state %>
    <%= f.input :event_loc_zip %>

    <br />
    <%= f.input :event_start_date %>
    <%= f.input :event_end_date %>

    <br />
    <%= f.input :event_website %>
    <%= f.input :event_description %>

    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1><%= @event.event_name %></h1><br />
    <p>
    	<b><%= @event.event_start_date.strftime("%A, %B %d, %Y") %></b>
	</p>
    <p>
    	<%= @event.event_loc_name %><br />
		<%= @event.event_loc_address %><br />
    	<%= @event.event_loc_city %>, <%= @event.event_loc_state %> <%= @event.event_loc_zip %><br />
    </p>
    <p>
		<%= link_to @event.event_website, "#{@event.event_website}", :target => "_blank" %>
    </p>
    <p>
		<%= @event.event_description %>
	</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Track Beer Fests | The Only App To Track All Your Beer Fests</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1">

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-64443259-1', 'auto');
	  ga('send', 'pageview');

	</script>


   
</head>
<body>

<header>
<div class="container">
	<div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
		<div class="logo">
		  <span class="symbol"></span>
		  <h1 class="title">
		    <%= link_to 'Track Beer Fests', root_path %>
		  </h1>
		</div>
	</div>
	<div class="hidden-xs col-sm-6 col-md-6 col-lg-6 slogan">
	</div>
	<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 nav">
		<%= link_to 'Sign Up', signup_path, :class => 'btn btn-success', :role => 'button' %>
	</div>
</div>	
</header>

<hr style="margin-bottom:-10px;" />

<div class="container">
	 <span class="row">
		<% if flash[:error].present? %>
	     	<span class="col-xs-10 col-xs-offset-1 alert alert-danger">
	        	<%= flash[:error].html_safe %>
	    	</span>
	    <% elsif flash[:success].present? %>
	    	<span class="col-xs-10 col-xs-offset-1 alert alert-success">
	        	<%= flash[:success].html_safe %>
	    	</span>
	    <% end %>
	</span>

		<%= yield %>
	
</div>

<div class="footer">
	<div class="container">
		<div class='text-center'>
        	&copy; 2015 <%= link_to 'Track Beer Fests', root_path %>. All Rights Reserved.
        </div>
    </div>
</div>

</body>
</html>

app/views/pages/signup.html.erb
<h1 class="text-center">The App is Almost Ready!</h1>
<div class="col-xs-2"></div>
<div class="col-xs-8">
	<p>We are working hard to put together the Track Beer Fest app. We will be releasing a beta test of the app soon for select beer festivals. If you would like to be one of the first beer snobs to try out this app, sign up below to be placed on the priority access list.</p>
	<p><strong><em>Thanks for your interest!</em></strong></p>
</div>
<div class="col-xs-2"></div>

app/views/users/index.html.erb
<h1 class="text-center">The Only App to Track Your Beer Festivals</h1><br /><br /><br />

<div class="col-xs-12 col-sm-7">
	<div class="row">
		<div class="col-xs-4 col-sm-3">
			<div class="numberCircle">1</div>
		</div>
		<div class="col-xs-8 col-sm-9 home-points">
			<span class="home-points-headline">Find Upcoming Festivals</span>
			<br />
			You will have access to a list of upcoming beer fests. Get advanced notice of which festivals will be coming to your area.
		</div>
	</div>

	<div class="row">
		<div class="col-xs-4 col-sm-3">
			<div class="numberCircle">2</div>
		</div>
		<div class="col-xs-8 col-sm-9 home-points">
			<span class="home-points-headline">Pre-Select Beers You Want to Try</span>
			<br />
			Access the list of breweries and what they are bringing. Add beers you would like to try to your wishlist ahead of time.
		</div>
	</div>

	<div class="row">
		<div class="col-xs-4 col-sm-3">
			<div class="numberCircle">3</div>
		</div>
		<div class="col-xs-8 col-sm-9 home-points">
			<span class="home-points-headline">Rate the Beers You Sample</span>
			<br />
			Rate and take notes about the beers you try so you know which ones to pick up when you get home.
		</div>
	</div>

	<br />

	<div class="row">
		<span class="hidden-xs col-sm-3"></span>
		<div class="col-xs-12 col-sm-9">
			<%= link_to 'Track Your Next Beer Fest!', signup_path, :class => 'btn btn-success btn-block', :type => 'button' %>
		</div>
	</div>

</div>


<div class="col-xs-12 col-sm-5">
	<%= image_tag 'beer.JPG', :class => 'img-responsive img-rounded home-img' %>
</div>

<br class="clear" />
<br />
<br />
<br />

app/views/users/signup.html.erb
<h1 class="text-center">The App is Almost Ready!</h1><br /><br /><br />
<div class="hidden-xs col-sm-2"></div>
<div class="col-xs-12 col-sm-8">
	<p>We are working hard to put together the Track Beer Fests app. A beta version will be released soon for select beer festivals. If you would like to be one of the first to try out this app, <strong>sign up below to be placed on the priority access list.</strong></p>

	<br />

	<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//trackbeerfests.us11.list-manage.com/subscribe/post?u=3a864c4623198f951203b95ce&amp;id=4bfbd8687a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Enter Your Email Address</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_3a864c4623198f951203b95ce_4bfbd8687a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Get Priority Access" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
</div>
<div class="hidden-xs col-sm-2"></div>

<br class="clear" /><br /><br /><br />

app/views/users/success.html.erb
<h4 class="text-center" style="color:green; margin-bottom:40px;"><strong>You have been added to the priority access list!</strong></p>

<h1 class="text-center" style="margin-bottom:-20px;">Tell Your Friends About the Track Beer Fests App</h1><br /><br /><br />

<span class ="row">
	<h3 class ="text-center">Share on Social Media</h3>
	<div class="col-xs-3"></div>
	<div class="col-xs-6 middleimages">
		<!-- Twitter -->
		<a href="http://twitter.com/home?status=http://www.trackbeerfests.com" title="Share on Twitter" target="_blank" class="btn btn-twitter" style="margin:10px;"><i class="fa fa-twitter"></i> Twitter</a>
		 <!-- Facebook -->
		<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.trackbeerfests.com" title="Share on Facebook" target="_blank" class="btn btn-facebook" style="margin:10px;"><i class="fa fa-facebook"></i> Facebook</a>
		<!-- Google+ -->
		<a href="https://plus.google.com/share?url=http://www.trackbeerfests.com" title="Share on Google+" target="_blank" class="btn btn-googleplus" style="margin:10px;"><i class="fa fa-google-plus"></i> Google+</a>
	</div>
	<div class="col-xs-3"></div>
</span>

<br />

<span class="row">
	<h3 class ="text-center">Or Copy This in an Email</h3>
	<div class="hidden-xs col-sm-2"></div>
	<div class="col-xs-12 col-sm-8 middleimages">
		<p style="padding:20px; margin-top:15px; border: 1px solid #C0C0C0;">Have you heard of Track Beer Fests? It's the only app to track your beer festivals. You can find upcoming festivals, pre-select beers you want to try, and rate the beers you sample. It's not released yet, but I just signed up for priority access. You can sign up here: <%= link_to 'Track Beer Fests', root_path %>.</p>
	</div>
	<div class="hidden-xs col-sm-2"></div>
</span>

<br />
<br />
<br />
<br />

app/views/users/thanks.html.erb
<h4 class="text-center" style="color:green; margin-bottom:20px;"><strong>Almost Finished</strong></p>
<h4 class="text-center" style="color:green; margin-bottom:40px;">We just need you to confirm your email address. Please check your email for the link to confirm.</p>

<h1 class="text-center" style="margin-bottom:-20px;">Tell Your Friends About the Track Beer Fests App</h1><br /><br /><br />

<span class ="row">
	<h3 class ="text-center">Share on Social Media</h3>
	<div class="col-xs-3"></div>
	<div class="col-xs-6 middleimages">
		<!-- Twitter -->
		<a href="http://twitter.com/home?status=http://www.trackbeerfests.com" title="Share on Twitter" target="_blank" class="btn btn-twitter" style="margin:10px;"><i class="fa fa-twitter"></i> Twitter</a>
		 <!-- Facebook -->
		<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.trackbeerfests.com" title="Share on Facebook" target="_blank" class="btn btn-facebook" style="margin:10px;"><i class="fa fa-facebook"></i> Facebook</a>
		<!-- Google+ -->
		<a href="https://plus.google.com/share?url=http://www.trackbeerfests.com" title="Share on Google+" target="_blank" class="btn btn-googleplus" style="margin:10px;"><i class="fa fa-google-plus"></i> Google+</a>
	</div>
	<div class="col-xs-3"></div>
</span>

<br />

<span class="row">
	<h3 class ="text-center">Or Copy This in an Email</h3>
	<div class="hidden-xs col-sm-2"></div>
	<div class="col-xs-12 col-sm-8 middleimages">
		<p style="padding:20px; margin-top:15px; border: 1px solid #C0C0C0;">Have you heard of Track Beer Fests? It's the only app to track your beer festivals. You can find upcoming festivals, pre-select beers you want to try, and rate the beers you sample. It's not released yet, but I just signed up for priority access. You can sign up here: <%= link_to 'Track Beer Fests', root_path %>.</p>
	</div>
	<div class="hidden-xs col-sm-2"></div>
</span>

<br />
<br />
<br />
<br />